const emptyForm = {
  name: "",
  slug: "",
  shortDescription: "",
  thumbnail: "",
  category: "",
  techStack: "",
  featured: false,
  liveUrl: "",
  githubUrl: "",
  overview: "",
  caseStudy: "",
  problem: "",
  solution: "",
  architecture: "",
  keyFeatures: "",
  challenges: "",
  results: "",
  gallery: "",
  sortOrder: 0,
  isPublished: true,
};

export const projectToForm = (project) => ({
  name: project.name ?? "",
  slug: project.slug ?? "",
  shortDescription: project.shortDescription ?? "",
  thumbnail: project.thumbnail ?? "",
  category: project.category ?? "",
  techStack: (project.techStack ?? []).join(", "),
  featured: project.featured ?? false,
  liveUrl: project.liveUrl ?? "",
  githubUrl: project.githubUrl ?? "",
  overview: project.overview ?? "",
  caseStudy: project.caseStudy ?? "",
  problem: project.problem ?? "",
  solution: project.solution ?? "",
  architecture: project.architecture ?? "",
  keyFeatures: (project.keyFeatures ?? []).join("\n"),
  challenges: (project.challenges ?? []).join("\n"),
  results: (project.results ?? []).join("\n"),
  gallery: (project.gallery ?? []).join("\n"),
  sortOrder: project.sortOrder ?? 0,
  isPublished: project.isPublished ?? true,
});

export const formToPayload = (form) => ({
  name: form.name.trim(),
  slug: form.slug.trim() || undefined,
  shortDescription: form.shortDescription.trim(),
  thumbnail: form.thumbnail.trim(),
  category: form.category.trim(),
  techStack: form.techStack,
  featured: form.featured,
  liveUrl: form.liveUrl.trim() || null,
  githubUrl: form.githubUrl.trim() || null,
  overview: form.overview.trim(),
  caseStudy: form.caseStudy.trim() || null,
  problem: form.problem.trim() || null,
  solution: form.solution.trim() || null,
  architecture: form.architecture.trim() || null,
  keyFeatures: form.keyFeatures,
  challenges: form.challenges,
  results: form.results,
  gallery: form.gallery,
  sortOrder: Number(form.sortOrder) || 0,
  isPublished: form.isPublished,
});

export default emptyForm;
